name: dokan
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^3.22.1
  get_storage: any
  google_sign_in: ^4.5.0
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  flutter_facebook_login: ^3.0.0
  cloud_firestore: ^3.1.5
  sqflite: ^1.3.2+2
  path: ^1.7.0
  shared_preferences: ^0.5.4+8
  flutter_svg: ^0.19.2+1
  status_change: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/images/
   - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/CairoRegular.ttf
